var DUOGUAN_HOST_URL = "https://x.duoguan.com";
module.exports = {


duoguan_user_token: "gh_f142ac0c7633",
 
//  duoguan_user_token: "gh_1a5b739d135c",
  duoguan_share_info:[],
  duoguan_auth_login_url:DUOGUAN_HOST_URL + "/index.php/home/weixin/slogin",
  duoguan_Launch_log_url:DUOGUAN_HOST_URL + "/index.php?s=/home/index/logs_on",
  duoguan_get_user_menu_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanUser/Api/getUserMenuList.html",
  duoguan_swiper_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanSwiper/DuoguanSwiper/dataApi.html",
  duoguan_cms_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanCms/DuoguanCms/dataApi.html",
  duoguan_cms_cate_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanCms/DuoguanCms/dataApiCate.html",
  duoguan_cms_read_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanCms/DuoguanCms/dataApiRead.html",
  duoguan_comment_add_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanCms/Comment/dataApiCommentAdd.html",
  duoguan_comment_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanCms/Comment/dataApiCommentList.html",
  duoguan_comment_good_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanCms/Comment/dataApiCommentGood.html",
  duoguan_user_info_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanUser/Api/getUserInfo.html",
  duoguan_user_info_post_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanUser/Api/editUserInfo.html",
  duoguan_get_user_paylog_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanUser/Api/getUserPaylog.html",
  duoguan_make_paydata_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanUser/Api/makePayData.html",
  duoguan_user_address_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/getAddressList.html",
  duoguan_user_address_add_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/addAddress.html",
  duoguan_user_address_info_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/getAddressInfo.html",
  duoguan_user_address_del_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/delAddress.html",
  duoguan_get_user_postlist_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/getUserPostList.html",
  duoguan_get_user_orderlist_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/getUserOrderList.html",
  duoguan_delete_user_order_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/deleteUserOrder.html",
  duoguan_shouhuo_user_order_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/shouhuoUserOrder.html",
  duoguan_post_comment_order:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/postComment.html",
  duoguan_get_bbs_cate_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/getCateList.html",
  duoguan_get_bbs_gonggao_id:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/getGongGaoId.html",
  duoguan_get_bbs_cate_two_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/getCateTwoList.html",
  duoguan_get_bbs_postlist_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/getPostList.html",
  duoguan_check_bbs_manage_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/checkManage.html",
  duoguan_bbs_post_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/bbsPost.html",
  duoguan_imgupload_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/imgUpload.html",
  duoguan_post_info_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/postInfo.html",
  duoguan_post_replyadd_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/replyAdd.html",
  duoguan_post_replylist_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/replyList.html",
  duoguan_post_xihuan_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/postXihuan.html",
  duoguan_post_report_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/postReport.html",
  duoguan_post_del_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/Weiba/Api/postDel.html",
  duoguan_get_shop_cate_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/getCateList.html",
  duoguan_get_good_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/getGoodsList.html",
  duoguan_get_good_info_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/getGoodsInfo.html",
  duoguan_add_good_cart_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/addGoodsCart.html",
  duoguan_get_cart_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/getCartList.html",
  duoguan_del_cart_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/delCartList.html",
  duoguan_edit_cart_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/editCartList.html",
  duoguan_get_shop_config_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/Api/getConfig.html",
  duoguan_order_post_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/postOrder.html",
  duoguan_order_info_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/orderInfo.html",
  duoguan_make_order_pay_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/makePay.html",
  duoguan_get_address_list_url:DUOGUAN_HOST_URL + "/index.php?s=/addon/DuoguanShop/OrderApi/getAddressList.html",
}